### ISSUE TITLE
Setup environment for Integration testing

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/provenance-service#13]
#### Description
_Describe the issue or task at hand with dependencies and possible links to code/external/internal sources._
#### DoD
_Itemized things or artifacts of the task at hand, what one expects to achieve - tangible output._
#### Testing
_How one would test that the things/artifacts have been achieved. Options (Peer review, Unit Test, BDD testing, Integration Test)._

**Comment by blankdots** [comment]
```yml
version: '2'
services:
  mysql:
    image: attxproject/unified-views-mariadb:stable-1.2
    ports:
      - 3306:3306
    # volumes:
    #   - ./uv-data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iamroot!

  shared:
    image: attxproject/unified-views-shared:stable-1.2

  backend:
    image: attxproject/unified-views-backend:stable-1.2
    links:
      - mysql:mysql
    volumes_from:
      - mysql
      - shared

  frontend:
    image: attxproject/unified-views-frontend:stable-1.2
    volumes_from:
      - backend
      - shared
    ports:
      - 8080:8080
    depends_on:
      - shared
      - mysql

  attx-dpus:
    image: attx-dev:5000/uv-attx-dpus:latest
    depends_on:
      - mysql
      - backend
  messagebroker:
    image: rabbitmq:3.6.11-management
    ports:
      - '4369:4369'
      - '5671:5671'
      - '5672:5672'
      - '15671:15671'
      - '15672:15672'
      - '25672:25672'
    environment:
        - RABBITMQ_DEFAULT_USER=user
        - RABBITMQ_DEFAULT_PASS=password
  fuseki:
    image: attxproject/attx-fuseki:fuseki3.4.0
    environment:
      - ADMIN_PASSWORD=pw123
    ports:
      - 3030:3030
  graphmanager:
    image: attx-dev:5000/gm-api:latest
    ports:
      - 4302:4302
    depends_on:
      - messagebroker
    volumes:
        - /attx-sb-shared:/attx-sb-shared
    environment:
      - MHOST=messagebroker
      - GHOST=fuseki
    links:
      - messagebroker:messagebroker
  # rmlservice:
  #   image: attx-dev:5000/rml-service:dev
  #   depends_on:
  #       - messagebroker
  #       - provservice
  #   environment:
  #       - BROKER_URL=tcp://messagebroker:61616
  #   links:
  #     - messagebroker:messagebroker
  provservice:
    image: attx-dev:5000/provenance-service:latest
    depends_on:
        - messagebroker
        - fuseki
    environment:
        - MHOST=messagebroker
        - GHOST=fuseki
    links:
      - messagebroker:messagebroker
  uvprov:
    image: attx-dev:5000/uv-prov:latest
    ports:
      - 4301:4301
    depends_on:
      - messagebroker
      - provservice
    environment:
      - MHOST=messagebroker
      - DBHOST=mysql
    links:
      - messagebroker:messagebroker
```
