### ISSUE TITLE
Testing provenance service in a distributed environment

### ISSUE THREAD

**Issue by jkesanie** [ATTX-project/provenance-service#3]
#### Description
Testing provenance service in Kontena cloud and cPouta (Swarm). Run mock message provider and provenance service in order to test HA capabilities of platforms and the message persistance. 

For example: Is the infra able to automatically start up a new instance of ProvService if we delete the old container manually? Are the messages sent during the absence of the service preserved? Load balancing?

#### DoD

Report.

**Comment by blankdots** [comment]
@jkesanie @joasilva 
provenance image for testing purposes pushed to private repo `attx-dev:5000/prov-service:dev` (it has a hard requirement that the messaging service name be `messagingservice`, we can add it as a parameter later, for now it will remain like that).
and docker-compose file available below. I am using version 3 because there is a need for `depends_on` parameter (maybe there is another way to make it work) in order for the `provservice` and `rmlservice` to start after the `messagebroker`.
```yml
version: '3'
services:
  messagebroker:
    image: attx-dev:5000/mom:latest
    ports:
      - '8161:8161'
      - '61616:61616'
      - '5672:5672'
      - '61613:61613'
      - '1883:1883'
      - '61614:61614'
  rmlservice:
    image: attx-dev:5000/rml-service:dev
    depends_on:
        - messagebroker
    environment:
        - BROKER_URL=tcp://messagebroker:61616
    links:
      - messagebroker:messagebroker
  provservice:
    image: attx-dev:5000/prov-service:dev
    depends_on:
        - messagebroker
        - rmlservice
    links:
      - rmlservice:rmlservice
      - messagebroker:messagebroker
```
The whole setup currently might be missing something because, even though the services connect to the `messagebroker`, `provservice` is not receiving any messages from `rmlservice` or no messages are sent - @jkesanie ideas ? (tried sending a message from the UI - the provservice receives it and does its thing).

**Comment by joasilva** [comment]
Here's the YML file for Kontena:
```
version: 0.1.1
stack: attxproject/provenance
services:
  messagebroker:
    image: attxproject/mom:0.1
    ports:
      - '8161:8161'
      - '61616:61616'
      - '5672:5672'
      - '61613:61613'
      - '1883:1883'
      - '61614:61614'
  rmlservice:
    image: attxproject/rml-service:dev
    depends_on:
        - messagebroker
    environment:
        - BROKER_URL=tcp://messagebroker:61616
    links:
      - messagebroker:messagebroker
  provservice:
    image: attxproject/prov-service:dev
    depends_on:
        - messagebroker
        - rmlservice
    links:
      - rmlservice:rmlservice
      - messagebroker:messagebroker
```
